add words_ps3.txt and initial ps3
danilomizin/practice pull request #13
Opened 2020-12-22 09:07 UTC by danilomizin

2020-12-22 22:43 UTC, MaxNGit requested changes
Finished reviewing.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +            return hand
You can initially add wildcard to hand and reduce count of vowels in `for` loop.
It will be more effective and simple.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +    for litter in word.lower():
By `litter` do you mean `letter`?

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +        if litter in new_hand.keys() and new_hand[litter] > 0:
You can remove `.keys()`

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +            return False
There is a chance to use regular expressions.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +            if (litter not in hand.keys()) or word.count(litter) > hand[litter]:
You can remove one pair of brackets. Firstly Python process `not`, then `and`, then `or` logic operators.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +        user_word = str(input("Enter word, or “!!” to indicate that you are finished:"))
Bare `input` takes input from console as string.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +            print(user_word, "earned", str(get_word_score(user_word, calculate_handlen(hand))) + ".", " Total:",
To simplify `print`, use formatting.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +            print("This is not valid word. Please choose another word", "\n")
There is no need in `\n` in the end, as print automatically move cursor to the next line in console.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +        return play_hand(update_hand(hand, user_word), word_list, count_points)
It would be better to replace recursion with loop.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +    You may assume that the input word is always either a string of letters,
You can remove long and unnecessary parts of docs. to function.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +            type_letter = CONSONANTS
You can delete such conditions and make one instruction.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +    while True:
Such `while True:` condition is not a good practice.

2020-12-22 22:43 UTC, MaxNGit commented on ps3.py
> +        print("Total score for this hand:", count_of_hand, "\n------")
Divide one print to several prints for better visual perception.

2020-12-23 15:42 UTC, danilomizin commented
> Finished reviewing.

Changed code to the your requirements.

2020-12-24 15:22 UTC, MaxNGit requested changes
Finished reviewing.

2020-12-24 15:22 UTC, MaxNGit commented on ps3.py
> +            return hand
What if the count of specific vowel is not 1?
There is a chance that letters will be set like {'a': 3, 'b': 1, ...}

2020-12-24 15:22 UTC, MaxNGit commented on ps3.py
> +        if letter in new_hand and new_hand[letter] > 0:
Use `new_hand.get(letter, 0)` instead of this. There is a chance that the letter in word will not be in hand, and Python will throw an error.

2020-12-24 15:22 UTC, MaxNGit commented on ps3.py
> +            if letter not in hand or word.count(letter) > hand[letter]:
The same mistake. Fix this KeyError.

2020-12-24 15:22 UTC, MaxNGit commented on ps3.py
> +    * The hand is displayed.
Remove such long and unnecessary parts of docs.

2020-12-24 15:22 UTC, MaxNGit commented on ps3.py
> +            print(f"{user_word} earned {str(get_word_score(user_word, calculate_handlen(hand)))} ."
These instructions are repeating. It will be more simple to decrale new var with `get_word_score` value and pass it here.

2020-12-24 21:16 UTC, closed without merging