Feature/hangman piustonen
danilomizin/practice pull request #7
Opened 2020-11-29 20:45 UTC by piustonen

new adding

2020-12-03 21:00 UTC, Hozhyi requested changes

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> -    '''
I believe these comments were quiet valuable, why you removed them?

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
>      wordlist = line.split()
Not all comments is worth to remove. Only those which won't will be needed in future

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +        flag = False
All this block can be simplified to `if letter in letters_guessed`

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +            s += "_ "
Try to avoid string concatenating in loop

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +    pass
Why it is needed here?

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +    return secret_word
Effectively you could just `return s`

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +    s = ""
Please - avoid 1 letter variables

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +        import string
Why you decided to move that import here?

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +        print(''.join(x))
`string.ascii_lowercase` - is already a string. Why you decided convert it to list, and than split it back to string?

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +        import string
You could have this `import` only once in the top of file

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +        print(y)
It shouldn't print it, it only should return it

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +        z = list(string.ascii_lowercase)
Effectively - you could just leave that scenario, as it will include the previous one

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +        for elements in letters_guessed:
It's not elements, it's a one element. And that's not just element - it's some symbol

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +            del z[z.index(elements.lower())]
That could be a good solution, but this operation is complex and time consuming. Try implementing that without deletion

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
>      '''
This function is quite long, it should be smaller (up to 30 lines long)

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +    letters_guessed = []
Do you think that `list` is the best container here?

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +    guesses_point = 6
I'd add a constants for these 3 and 6

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +    print("Welcome to the game Hangman!\nI am thinking of a word that is", len(secret_word), "letters long")
Could you have a separate `print` per line? It would be more readable

2020-12-03 21:00 UTC, Hozhyi commented on hangman.py
> +            break
Could you have the game result output to be separate from game iterations loop?

2020-12-22 19:13 UTC, Hozhyi requested changes

2020-12-22 19:13 UTC, Hozhyi commented on hangman.py
> +            break
Effectively you could just write here `return False`, and no need in additional `flag`

2020-12-22 19:13 UTC, Hozhyi commented on hangman.py
> +        counter += 1
Seems like you can write this code without this `counter` as it just makes this code more complicated.

2020-12-22 19:13 UTC, Hozhyi commented on hangman.py
> +            formed_word += HIDDEN_LETTER
This concatenating of strings in loop will produce additional garbage. Try to avoid that

2020-12-22 19:13 UTC, Hozhyi commented on hangman.py
> +    import string
Why do you moved that line to here? It worth having it in the top of file

2020-12-22 19:13 UTC, Hozhyi commented on hangman.py
> +            y = ''.join(x)  # ''
Could you avoid writing comments that are not useful?

2020-12-22 19:13 UTC, Hozhyi commented on hangman.py
> +    x = list(string.ascii_lowercase)
1 letter variable

2020-12-22 19:13 UTC, Hozhyi commented on hangman.py
> +            del x[x.index(symbol.lower())]
This deleting from list is not as easy operation. Could you implement different approach? E.g. adding all needed letters to list

2020-12-22 19:13 UTC, Hozhyi commented on hangman.py
> +        print("Possible word matches are:", " ".join(random_words))
I expected to see it in Danilo's changes only, why you made some changes here? Danilo already merged his changes to develop, so you can re-base your branch on the top of develop, and you will have all code from Danilo

2020-12-25 18:47 UTC, MaxNGit requested changes
Finished reviewing.
Sorry, but I could not see the whole file, but only changes. In some places I wrote "Line:..." find this line and make changes here.

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
> +    if len(list_word) < 30:
Add docs.

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
> +    # secret_word while you're doing your own testing)
What does this comment mean?

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
> +        print("Possible word matches are:", " ".join(random_words))
Line 137: add comment to `count_star` var

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
> +    elif not is_word_guessed(secret_word, letters_guessed) and guesses_point <= 0:
Remove unnecassary condition

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
>      warnings_point = 3
Use constants to set value of these vars.

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
>      my_word: string with _ characters, current guess of secret word
Line 227: you can iterate not only through index but also throuhg elements it iterable objects. Simplify conditions.

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
Line 248: don't use True in conditions

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
>      while True:
It is not good to use True in condition of while loop. Change it to boolean var.

2020-12-25 18:47 UTC, MaxNGit commented on hangman.py
>                  return False
Line 264: remove unnecassary conditions

2020-12-26 14:11 UTC, MaxNGit requested changes

2020-12-26 14:11 UTC, MaxNGit commented on hangman.py
>  def warnings(value_mistake, warnings_point, guesses_point, secret_word, letters_guessed):
Add docs about params  and functions (check also other functions)

2020-12-26 14:11 UTC, MaxNGit commented on hangman.py
> +        for i in range(30):
Use list slicing not loop

2020-12-26 14:11 UTC, MaxNGit commented on hangman.py
> +        print("Possible word matches are:", " ".join(random_words))
Line 141: add comment about `count_star` var

2020-12-26 14:11 UTC, MaxNGit commented on hangman.py
>      my_word: string with _ characters, current guess of secret word
Line 231: simplify condition

2020-12-26 14:11 UTC, MaxNGit commented on hangman.py
>      for word in list(wordlist):
`wordlist` is already list

2020-12-26 14:11 UTC, MaxNGit commented on hangman.py
>      while True:
Don't use True in while loop condition

2020-12-27 09:16 UTC, MaxNGit requested changes

2020-12-27 09:16 UTC, MaxNGit commented on hangman.py
> +                                 " play hangman with hints input 'hints':").strip()
Lines of input are repeating. It is not good.

2020-12-27 11:24 UTC, MaxNGit approved these changes

2020-12-27 11:37 UTC, merged